kind: pipeline
type: docker
name: default

steps:
- name: install dependency
  image: python:3.9
  commands:
  - pip install -r requirements.txt -t .


- name: django-background
  image: python:3.9
  detach: true
  commands:
  - python manage.py runserver 0.0.0.0:8000

- name: frontend
  image: alpine/curl:3.14
  commands:
  - sleep 10
  - "curl -I -H \"Host: localhost\" http://django-background:8000/ > a.log"

- name: runner
  image: alpine
  commands:
    - echo "Hello World"
    - cat a.log
    - echo $env
  # depends_on:
  # - frontend
  # - backend

# - name: notify
#   image: plugins/slack
#   settings:
#     webhook:
#       from_secret: webhook
#   depends_on:
#   - frontend
#   - backend
