kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: python:3.9
  detach: true
  commands:
  - pip install -r requirements.txt
  - python manage.py runserver

- name: frontend
  image: alpine/curl:3.14
  commands:
  - curl http://backend:8080/

- name: runner
  image: alpine
  commands:
    - echo "Hello World"
  # depends_on:
  # - frontend
  # - backend

# - name: notify
#   image: plugins/slack
#   settings:
#     webhook:
#       from_secret: webhook
#   depends_on:
#   - frontend
#   - backend
