kind: pipeline
type: docker
name: default

steps:
- name: install dependency
  image: python:3.9
  commands:
  - pip install -r requirements.txt -t .

- name: django-background
  image: python:3.9
  detach: true
  commands:
  - python manage.py runserver 0.0.0.0:8000

- name: wait for django
  image: alpine
  commands:
    - sleep 10

- name: check if django is running
  image: alpine/curl:3.14
  commands:
  - "curl -I -H \"Host: localhost\" http://django-background:8000/"
  - echo "blah blah blah" > a.log

- name: test 1
  image: alpine
  commands:
    - echo "Hello World"
    - cat a.log
    - env

# - name: test 2
#   image: alpine
#   commands:
#     - exit 1

- name: test 3
  image: alpine
  commands:
    - exit 0

- name: on-failed
  image: alpine
  commands:
    - echo "failed"
    - env
  when:
    status:
    - failure
  # depends_on:
  # - frontend
  # - backend

# - name: notify
#   image: plugins/slack
#   settings:
#     webhook:
#       from_secret: webhook
#   depends_on:
#   - frontend
#   - backend
